services:
  server:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/server-app
      - /server-app/node_modules
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client-app
      - /client-app/node_modules
    environment:
      - NODE_ENV=development
